# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(2) do |config|
  

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  #Give it a host name
  config.vm.hostname = "TestServer"

  #Forward Ports Go Here
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4443

  #Hardware config provisioning block
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  #Disable the synced folder stuff So It Doesn't Spew Errors
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #Shell Provisioning
  config.vm.provision "shell",
    inline: "yum update -y && yum upgrade -y"
  end
