# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(2) do |config|
  

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  #Give it a host name
  config.vm.hostname = "ubuntutrusty"


  #Disable the synced folder stuff
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #initial config provisioning block 
  config.vm.provision "shell" do |s|
    s.inline = "echo Hello, Let us begin to provision!"
    s.inline = "apt-get update -y && apt-get upgrade -y"
  end

  #Initial ansible provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.sudo = true 
    ansible.playbook = "provisioning/main.yml"
  end
end
