# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

# Give all vms a 1GB of RAM and 2 CPUs.
  config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2
  end

# Whip up 3 basic CentOS nodes with a nat and private nic and 3 5GB Disks.
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos7"
      node.vm.network "private_network", ip: "192.168.50.10#{i}"
      node.vm.provider "virtualbox" do |vb|

        #Specify and Create Disks Here
        vb.customize ['createhd', '--filename', "host#{i}diskAA.vdi", 
        '--variant', 'Fixed', '--size', 5 * 1024]
        vb.customize ['createhd', '--filename', "host#{i}diskBB.vdi", 
        '--variant', 'Fixed', '--size', 5 * 1024]
        vb.customize ['createhd', '--filename', "host#{i}diskCC.vdi", 
        '--variant', 'Fixed', '--size', 5 * 1024]

        #Attach Disks From Here With Port and Disk Letter
        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 1,
        '--device', "0", '--type', 'hdd', '--medium', "host#{i}diskAA.vdi"]
        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 2,
        '--device', "0", '--type', 'hdd', '--medium', "host#{i}diskBB.vdi"]
        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 3,
        '--device', "0", '--type', 'hdd', '--medium', "host#{i}diskCC.vdi"]
      end
    end
  end

    ############# Provisioning ##################
    config.vm.provision "shell" do |s|
      s.inline = "yum update -y && yum upgrade -y"
    end 

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/main.yml"
      ansible.extra_vars = {ansible_ssh_user: 'vagrant'}
      ansible.sudo = true
    end
end
