# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(2) do |config|
  

  config.vm.box = "debian/jessie64"

  #VirtualBox host name. Hostsupdater requires plugin and run with sudo.
  #"vagrant plugin install vagrant-hostsupdater"
  config.vm.hostname = "www.node1.ru"
  config.hostsupdater.aliases = ["alias.node1.ru"]

  config.vm.network :private_network, ip: "192.168.3.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4443

  #Hardware config for VirtualBox provisioning block
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  #Disable the synced folder stuff in VBox so it doesn't spew errors
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #Shell Bootstrap Provisioning; Use Ansible For More Intense Stuff
  config.vm.provision "shell",
    inline: "apt-get update -y"
end
