# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

# Give all vms a 1GB of RAM and 2 CPUs.
  config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2
  end

# Whip up 3 basic CentOS nodes with a nat and private nic.
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.network "private_network", ip: "192.168.50.10#{i}"
    end
  end


###########################################################
#             Provisioning Section Below
###########################################################

  config.vm.provision "shell" do |s|
    s.inline = "yum update -y && yum upgrade -y"
  end 

# Then provision with an Ansible Playbook test.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.extra_vars = {ansible_ssh_user: 'vagrant'}
    ansible.sudo = true
  end

end
